export const Toolbar = [
  ['image'],
  [{ font: [] }, { header: [1, 2, 3, 4, 5, 6, false] }],
  ['bold', 'italic', 'underline', 'strike', 'code-block', 'link'],
  [{ color: [] }, { background: [] }, { align: [] }],
  [
    { list: 'ordered' },
    { list: 'bullet' },
    'blockquote',
    { indent: '+1' },
    { indent: '-1' },
  ],
  [{ script: 'sub' }, { script: 'super' }],
  ['clean'],
];
export const Formats = [
  'header',
  'bold',
  'italic',
  'underline',
  'strike',
  'blockquote',
  'code-block',
  'list',
  'ordered',
  'bullet',
  'script',
  'indent',
  'link',
  'image',
  'color',
  'background',
  'font',
  'align',
  'clean',
];
